---
version: '2.0'

services:

 apache:
  
  container_name: mongodb
  
  build:
    context: .
    dockerfile: dockerfile

  ports:
       - 80:80
  
  volumes:
      - .:/var/www/html

  networks:
     - bridge-conn


networks:
   bridge-conn:
    driver: bridge
