version: '3'

services:
  apache:

    build:
      context: .
      dockerfile: "dockerfile"

    container_name: "apache1"

    volumes:
      - sharenew:/var/www/html


    links:
      - apache_second:connect

  
    ports:
      - "80:80"

    networks:
      app_net:
        ipv4_address: 10.0.0.4

    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost"]
     interval: 1m30s
     timeout: 10s
     retries: 3

  apache_second:

    build:
      context: .
      dockerfile: "dockerfile"

    container_name: "apache2"

    volumes:
      - sharenew:/var/www/html

  
    ports:
      - "82:80"

    networks:
      app_net:
        ipv4_address: 10.0.0.3

    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost"]
     interval: 1m30s
     timeout: 10s
     retries: 3

volumes:
  sharenew:  

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 10.0.0.0/24
